# Generated by Django 6.0.2 on 2026-02-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPNLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID único da sessão no FortiAnalyzer', max_length=255, unique=True)),
                ('user', models.CharField(db_index=True, help_text='Nome de usuário da VPN', max_length=255)),
                ('source_ip', models.GenericIPAddressField(help_text='IP de origem da conexão')),
                ('start_time', models.DateTimeField(db_index=True, help_text='Data e hora de início da conexão')),
                ('end_time', models.DateTimeField(blank=True, help_text='Data e hora de fim da conexão', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duração em segundos', null=True)),
                ('bandwidth_in', models.BigIntegerField(default=0, help_text='Bytes recebidos')),
                ('bandwidth_out', models.BigIntegerField(default=0, help_text='Bytes enviados')),
                ('status', models.CharField(help_text='Status da conexão (ex: tunnel-up, tunnel-down)', max_length=50)),
                ('ad_department', models.CharField(blank=True, help_text='Departamento do usuário (AD)', max_length=255, null=True)),
                ('ad_email', models.EmailField(blank=True, help_text='Email do usuário (AD)', max_length=254, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Dados brutos do log')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log de VPN',
                'verbose_name_plural': 'Logs de VPN',
                'ordering': ['-start_time'],
            },
        ),
    ]
