# Generated by Django 6.0.2 on 2026-02-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnlog',
            name='ad_display_name',
            field=models.CharField(blank=True, help_text='Nome completo do usuário (AD)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vpnlog',
            name='ad_title',
            field=models.CharField(blank=True, help_text='Cargo do usuário (AD)', max_length=255, null=True),
        ),
    ]
