# Generated by Django 6.0.2 on 2026-02-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0002_vpnlog_ad_display_name_vpnlog_ad_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnlog',
            name='city',
            field=models.CharField(blank=True, help_text='Cidade de origem', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vpnlog',
            name='country_code',
            field=models.CharField(blank=True, help_text='Código do país (ISO)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vpnlog',
            name='country_name',
            field=models.CharField(blank=True, help_text='Nome do país', max_length=100, null=True),
        ),
    ]
