# Generated by Django 6.0.2 on 2026-02-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0003_vpnlog_city_vpnlog_country_code_vpnlog_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnlog',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, help_text='Data de início (para otimização)', null=True),
        ),
        migrations.AlterField(
            model_name='vpnlog',
            name='ad_department',
            field=models.CharField(blank=True, db_index=True, help_text='Departamento do usuário (AD)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vpnlog',
            name='ad_title',
            field=models.CharField(blank=True, db_index=True, help_text='Cargo do usuário (AD)', max_length=255, null=True),
        ),
    ]
