# Generated by Django 6.0.2 on 2026-02-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0004_vpnlog_start_date_alter_vpnlog_ad_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnlog',
            name='is_suspicious',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se o acesso é suspeito (país não confiável)'),
        ),
    ]
