# Generated by Django 5.1.5 on 2026-02-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0005_vpnlog_is_suspicious'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnlog',
            name='impossible_travel',
            field=models.BooleanField(db_index=True, default=False, help_text='Alerta de viagem impossível'),
        ),
        migrations.AddField(
            model_name='vpnlog',
            name='travel_speed',
            field=models.FloatField(blank=True, help_text='Velocidade estimada (km/h) entre conexões', null=True),
        ),
    ]
