# Generated by Django 5.1.5 on 2026-02-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0006_vpnlog_impossible_travel_vpnlog_travel_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VPNFailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, help_text='Usuário tentado', max_length=255)),
                ('source_ip', models.GenericIPAddressField(db_index=True, help_text='IP de origem')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Data e hora da falha')),
                ('reason', models.CharField(blank=True, help_text='Motivo (ex: bad-password)', max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Falha de Login VPN',
                'verbose_name_plural': 'Falhas de Login VPN',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='vpn_logs_vp_user_ca005e_idx'), models.Index(fields=['source_ip', 'timestamp'], name='vpn_logs_vp_source__9ede8f_idx')],
            },
        ),
    ]
