# Generated by Django 5.1.5 on 2026-02-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0007_alter_vpnlog_id_vpnfailure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnfailure',
            name='reason',
            field=models.CharField(blank=True, help_text='Motivo da falha (ex: bad-password)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vpnfailure',
            name='timestamp',
            field=models.DateTimeField(db_index=True, help_text='Carimbo de data/hora da falha'),
        ),
    ]
