# Generated by Django 5.1.5 on 2026-02-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0008_alter_vpnfailure_reason_alter_vpnfailure_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnlog',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Carimbo de data/hora do último batimento cardíaco (heartbeat)', null=True),
        ),
    ]
