# Generated by Django 5.1.5 on 2026-02-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0009_vpnlog_last_activity_alter_vpnfailure_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnfailure',
            name='ad_department',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vpnfailure',
            name='ad_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vpnfailure',
            name='ad_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vpnfailure',
            name='ad_title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vpnfailure',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
