# Generated by Django 5.1.5 on 2026-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0010_vpnfailure_ad_department_vpnfailure_ad_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnlog',
            name='travel_details',
            field=models.JSONField(blank=True, help_text='Contexto da viagem impossível (locais e tempos)', null=True),
        ),
        migrations.AlterField(
            model_name='vpnfailure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vpnlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
