# Generated by Django 5.1.5 on 2026-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0011_vpnlog_travel_details_alter_vpnfailure_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnfailure',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpnfailure',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpnlog',
            name='distance_km',
            field=models.FloatField(blank=True, help_text='Distância calculada entre conexões (km)', null=True),
        ),
        migrations.AddField(
            model_name='vpnlog',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude do IP de origem', null=True),
        ),
        migrations.AddField(
            model_name='vpnlog',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude do IP de origem', null=True),
        ),
    ]
