# Generated by Django 5.1.5 on 2026-02-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0012_vpnfailure_latitude_vpnfailure_longitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vpnlog',
            index=models.Index(fields=['user', 'start_date'], name='vpn_logs_vp_user_63c94e_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnlog',
            index=models.Index(fields=['is_suspicious', 'start_date'], name='vpn_logs_vp_is_susp_b31b77_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnlog',
            index=models.Index(fields=['impossible_travel', 'start_date'], name='vpn_logs_vp_impossi_de5dc4_idx'),
        ),
    ]
