# Generated by Django 6.0.2 on 2026-02-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('sqlserver', 'SQL Server')], max_length=20, verbose_name='Database Type')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('database_name', models.CharField(max_length=100, verbose_name='Database Name')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('encrypted_password', models.TextField(verbose_name='Password (Encrypted)')),
                ('is_configured', models.BooleanField(default=False)),
                ('configured_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Database Configuration',
                'verbose_name_plural': 'Database Configurations',
            },
        ),
        migrations.CreateModel(
            name='SetupProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('welcome', 'Welcome'), ('choose_db', 'Choose Database'), ('configure_db', 'Configure Database'), ('test_connection', 'Test Connection'), ('create_admin', 'Create Admin User'), ('complete', 'Complete')], default='welcome', max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Setup Progress',
                'verbose_name_plural': 'Setup Progress',
            },
        ),
    ]
