# Generated by Django 5.1.5 on 2026-02-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_alter_databaseconfiguration_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfiguration',
            name='is_retention_enabled',
            field=models.BooleanField(default=True, help_text='Se ativado, logs antigos serão excluídos diariamente.', verbose_name='Ativar Limpeza Automática'),
        ),
        migrations.AddField(
            model_name='databaseconfiguration',
            name='retention_days',
            field=models.PositiveIntegerField(default=90, help_text='Quantidade de dias que os logs permanecerão no banco de dados. (Ex: 90)', verbose_name='Dias de Retenção'),
        ),
    ]
