# Generated by Django 5.1.5 on 2026-02-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador (Slug)')),
                ('icon', models.CharField(default='📊', help_text='Emoji ou classe de ícone (ex: 📊, 🛡️, fa-solid fa-shield)', max_length=50, verbose_name='Ícone')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('url_name', models.CharField(help_text='Nome da rota Django (ex: dashboard:vpn_reports) ou URL absoluta', max_length=200, verbose_name='Rota/URL')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Módulo do Portal',
                'verbose_name_plural': 'Módulos do Portal',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
