# Generated by Django 5.1.5 on 2026-02-18 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRiskScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Usuário')),
                ('current_score', models.IntegerField(default=0, verbose_name='Score Atual')),
                ('risk_level', models.CharField(default='Low', max_length=20, verbose_name='Nível de Risco')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='Último Cálculo')),
                ('trend', models.CharField(default='Stable', max_length=10, verbose_name='Tendência')),
            ],
            options={
                'verbose_name': 'Score de Risco do Usuário',
                'verbose_name_plural': 'Scores de Risco dos Usuários',
                'ordering': ['-current_score'],
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_source', models.CharField(choices=[('ips', 'IPS'), ('antivirus', 'Antivirus'), ('webfilter', 'Web Filter'), ('vpn', 'VPN')], max_length=20)),
                ('event_id', models.CharField(blank=True, help_text='ID do evento original se disponível', max_length=100)),
                ('weight_added', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('user_risk_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.userriskscore')),
            ],
            options={
                'verbose_name': 'Evento de Risco',
                'verbose_name_plural': 'Eventos de Risco',
                'ordering': ['-timestamp'],
            },
        ),
    ]
