# Generated by Django 5.1.5 on 2026-02-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userriskscore_riskevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmodule',
            name='color',
            field=models.CharField(default='text-blue-500', help_text='Classe utilitária CSS ou cor em Hex (ex: text-blue-500, #ff0000, etc.)', max_length=50, verbose_name='Cor do Ícone'),
        ),
    ]
