# Generated by Django 5.1.5 on 2026-02-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_portalmodule_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portalmodule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riskevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userriskscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('group', models.CharField(choices=[('webfilter', 'Web Filter'), ('ips', 'IPS'), ('antivirus', 'Antivirus'), ('app-control', 'App Control'), ('vpn', 'VPN'), ('ad-auth', 'AD Auth'), ('risk', 'User Risk')], db_index=True, max_length=50)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('count', models.BigIntegerField(default=0)),
                ('volume', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica de Dashboard',
                'verbose_name_plural': 'Métricas de Dashboard',
                'indexes': [models.Index(fields=['group', 'metric_name', 'date'], name='dashboard_d_group_1a1ec9_idx')],
                'unique_together': {('date', 'group', 'metric_name', 'key')},
            },
        ),
    ]
