# Generated by Django 6.0.2 on 2026-02-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDirectoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(default='ldap.example.com', help_text='Endereço do DC', max_length=255)),
                ('port', models.IntegerField(default=389)),
                ('use_ssl', models.BooleanField(default=False, help_text='Usar LDAPS?')),
                ('base_dn', models.CharField(default='DC=example,DC=com', max_length=255)),
                ('bind_user', models.CharField(help_text='Usuário para bind (ex: CN=BindUser,OU=ServiceAccounts,DC=example,DC=com)', max_length=255)),
                ('bind_password', models.CharField(help_text='Senha do usuário de bind', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuração Active Directory',
                'verbose_name_plural': 'Configuração Active Directory',
            },
        ),
        migrations.CreateModel(
            name='FortiAnalyzerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='https://fortianalyzer.example.com', max_length=255)),
                ('port', models.IntegerField(default=443)),
                ('api_token', models.CharField(help_text='Token de API gerado no FortiAnalyzer', max_length=512)),
                ('verify_ssl', models.BooleanField(default=False, help_text='Verificar certificado SSL?')),
            ],
            options={
                'verbose_name': 'Configuração FortiAnalyzer',
                'verbose_name_plural': 'Configuração FortiAnalyzer',
            },
        ),
    ]
