# Generated by Django 6.0.2 on 2026-02-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortianalyzerconfig',
            name='adom',
            field=models.CharField(default='root', help_text='Nome do ADOM (ex: root)', max_length=100),
        ),
    ]
