# Generated by Django 6.0.2 on 2026-02-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_activedirectoryconfig_admin_group_dn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedirectoryconfig',
            name='admin_group_dn',
            field=models.CharField(default='CN=TI-Admins,OU=Groups,DC=example,DC=com', help_text='DN do grupo que terá acesso Admin', max_length=255, verbose_name='Grupo de Administradores'),
        ),
    ]
