# Generated by Django 6.0.2 on 2026-02-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_activedirectoryconfig_admin_group_dn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activedirectoryconfig',
            name='admin_group_dn',
        ),
    ]
