# Generated by Django 6.0.2 on 2026-02-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_remove_activedirectoryconfig_admin_group_dn'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortianalyzerconfig',
            name='trusted_countries',
            field=models.TextField(default='BR', help_text='Códigos de países confiáveis, separados por vírgula (ex: BR,US)'),
        ),
    ]
