# Generated by Django 5.1.5 on 2026-02-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_fortianalyzerconfig_trusted_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyslogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Ativar a recepção passiva de logs via Syslog UDP?')),
                ('port', models.IntegerField(default=5140, help_text='Porta UDP para escuta (Padrão 5140)')),
            ],
            options={
                'verbose_name': 'Configuração Syslog Receiver',
                'verbose_name_plural': 'Configuração Syslog Receiver',
            },
        ),
        migrations.AddField(
            model_name='fortianalyzerconfig',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Ativar a coleta ativa (Polling) via API do FortiAnalyzer?'),
        ),
    ]
