# Generated by Django 5.1.5 on 2026-02-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_syslogconfig_fortianalyzerconfig_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='ID/Serial Number do Dispositivo (ex: FGT60E...)', max_length=100, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Último IP de origem detectado')),
                ('device_type', models.CharField(default='fortigate', help_text='Fabricante/Tipo detectado', max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_authorized', models.BooleanField(default=True, help_text='Indica se este dispositivo é uma fonte confiável')),
            ],
            options={
                'verbose_name': 'Dispositivo Emissor (Inventory)',
                'verbose_name_plural': 'Dispositivos Emissores (Inventory)',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AlterModelOptions(
            name='fortianalyzerconfig',
            options={'verbose_name': 'Coleta via API (FortiAnalyzer)', 'verbose_name_plural': 'Coleta via API (FortiAnalyzer)'},
        ),
        migrations.AlterModelOptions(
            name='syslogconfig',
            options={'verbose_name': 'Coleta em Tempo Real (Syslog)', 'verbose_name_plural': 'Coleta em Tempo Real (Syslog)'},
        ),
    ]
