# Generated by Django 5.1.5 on 2026-02-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_knowndevice_alter_fortianalyzerconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowndevice',
            name='last_alert_message',
            field=models.CharField(blank=True, help_text='Último alerta de sistema (CPU/Memória/Link)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='knowndevice',
            name='last_alert_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
