# Generated by Django 5.1.5 on 2026-02-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_knowndevice_last_alert_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowndevice',
            name='conserve_mode',
            field=models.BooleanField(default=False, help_text='Indica se o dispositivo está em Conserve Mode'),
        ),
        migrations.AddField(
            model_name='knowndevice',
            name='cpu_status',
            field=models.CharField(default='normal', help_text='Estado da CPU (normal/alto)', max_length=50),
        ),
        migrations.AddField(
            model_name='knowndevice',
            name='link_status',
            field=models.CharField(default='normal', help_text='Estado dos Links (normal/alarme)', max_length=50),
        ),
        migrations.AddField(
            model_name='knowndevice',
            name='memory_status',
            field=models.CharField(default='normal', help_text='Estado da Memória (normal/alto)', max_length=50),
        ),
    ]
