# Generated by Django 5.1.5 on 2026-02-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_knowndevice_conserve_mode_knowndevice_cpu_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowndevice',
            name='monitored_ports',
            field=models.JSONField(blank=True, default=list, help_text="Lista de portas monitoradas: [{'name': 'wan1', 'alias': 'Internet'}]"),
        ),
    ]
