# Generated by Django 5.1.5 on 2026-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_knowndevice_monitored_ports'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Se ativado, logs antigos serão excluídos diariamente.', verbose_name='Ativar Limpeza Automática')),
                ('retention_days', models.PositiveIntegerField(default=90, help_text='Quantidade de dias que os logs permanecerão no banco de dados. (Ex: 90)', verbose_name='Dias de Retenção')),
            ],
            options={
                'verbose_name': 'Política de Retenção de Dados',
                'verbose_name_plural': 'Política de Retenção de Dados',
            },
        ),
    ]
