# Generated by Django on 2026-02-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_dataretentionconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataRetentionConfig',
        ),
    ]
