# Generated by Django 5.1.5 on 2026-06-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_delete_dataretentionconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnownDevice',
        ),
        migrations.DeleteModel(
            name='SyslogConfig',
        ),
    ]
