# Generated by Django 5.1.5 on 2026-06-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_delete_knowndevice_delete_syslogconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='activedirectoryconfig',
            name='ca_cert_file',
            field=models.FileField(blank=True, help_text='Faça o upload do certificado raiz da CA (formato .pem, .crt ou .cer)', null=True, upload_to='certs/', verbose_name='Certificado CA (PEM/CRT)'),
        ),
        migrations.AddField(
            model_name='activedirectoryconfig',
            name='validate_certificate',
            field=models.BooleanField(default=False, help_text='Exigir validação do certificado do AD (requer upload do certificado CA)', verbose_name='Validar Certificado SSL/TLS'),
        ),
    ]
