# Generated by Django 5.1.5 on 2026-06-29 19:37

import integrations.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_configauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedirectoryconfig',
            name='bind_password',
            field=integrations.fields.EncryptedCharField(help_text='Senha do usuário de bind', max_length=400),
        ),
        migrations.AlterField(
            model_name='fortianalyzerconfig',
            name='api_token',
            field=integrations.fields.EncryptedCharField(help_text='Token de API gerado no FortiAnalyzer', max_length=700),
        ),
    ]
