# Generated by Django 5.1.5 on 2026-02-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('ips', 'IPS'), ('antivirus', 'Antivirus'), ('webfilter', 'Web Filter')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Crítico'), ('high', 'Alto'), ('medium', 'Médio'), ('low', 'Baixo'), ('info', 'Informativo')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('src_country', models.CharField(blank=True, max_length=100)),
                ('dst_country', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_department', models.CharField(blank=True, max_length=255)),
                ('attack_name', models.CharField(blank=True, max_length=500)),
                ('attack_id', models.CharField(blank=True, max_length=100)),
                ('cve', models.CharField(blank=True, max_length=100)),
                ('virus_name', models.CharField(blank=True, max_length=500)),
                ('file_name', models.CharField(blank=True, max_length=500)),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('url', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(max_length=50)),
                ('raw_log', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento de Segurança',
                'verbose_name_plural': 'Eventos de Segurança',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'date'], name='security_ev_event_t_b8f125_idx'), models.Index(fields=['severity', 'date'], name='security_ev_severit_97ca43_idx'), models.Index(fields=['username', 'date'], name='security_ev_usernam_e23c77_idx'), models.Index(fields=['-timestamp'], name='security_ev_timesta_215529_idx')],
            },
        ),
    ]
