# Generated by Django 5.1.5 on 2026-02-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='ad_display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome de Exibição (AD)'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='ad_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cargo (AD)'),
        ),
    ]
