# Generated by Django 5.1.5 on 2026-02-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_events', '0002_securityevent_ad_display_name_securityevent_ad_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='app_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='app_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='app_risk',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='bytes_in',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='bytes_out',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('ips', 'IPS'), ('antivirus', 'Antivirus'), ('webfilter', 'Web Filter'), ('app-control', 'App Control')], db_index=True, max_length=20),
        ),
    ]
