# Generated by Django 5.1.5 on 2026-02-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_events', '0003_securityevent_app_category_securityevent_app_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADAuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, verbose_name='Usuário')),
                ('workstation', models.CharField(blank=True, max_length=255, verbose_name='Estação/Computador')),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failed', 'Falha'), ('locked', 'Conta Bloqueada')], db_index=True, max_length=20)),
                ('event_id', models.IntegerField(db_index=True, verbose_name='Event ID (Windows)')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem Original')),
                ('ad_department', models.CharField(blank=True, max_length=255)),
                ('ad_title', models.CharField(blank=True, max_length=255)),
                ('ad_display_name', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento de Autenticação AD',
                'verbose_name_plural': 'Eventos de Autenticação AD',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', 'timestamp'], name='security_ev_usernam_65b81f_idx'), models.Index(fields=['status', 'timestamp'], name='security_ev_status_0c2991_idx'), models.Index(fields=['event_id', 'timestamp'], name='security_ev_event_i_8b119d_idx')],
            },
        ),
    ]
