# Generated by Django 5.1.5 on 2026-02-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_events', '0004_adauthevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(db_index=True, max_length=255)),
                ('sid', models.CharField(max_length=150, unique=True)),
                ('is_privileged', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo do AD (Radar)',
                'verbose_name_plural': 'Grupos do AD (Radar)',
            },
        ),
        migrations.CreateModel(
            name='ADRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_groups', models.IntegerField(default=0)),
                ('privileged_users_count', models.IntegerField(default=0)),
                ('inactive_privileged_count', models.IntegerField(default=0)),
                ('disabled_privileged_count', models.IntegerField(default=0)),
                ('chart_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Snapshot de Risco AD',
                'verbose_name_plural': 'Snapshots de Risco AD',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ADUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('sid', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('last_logon', models.DateTimeField(blank=True, null=True)),
                ('pwd_last_set', models.DateTimeField(blank=True, null=True)),
                ('is_inactive', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_privileged', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário do AD (Radar)',
                'verbose_name_plural': 'Usuários do AD (Radar)',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='ADMemberOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='security_events.adgroup')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_groups', to='security_events.adgroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='security_events.aduser')),
            ],
            options={
                'verbose_name': 'Associação AD (Radar)',
                'verbose_name_plural': 'Associações AD (Radar)',
            },
        ),
    ]
