# Generated by Django 5.1.5 on 2026-02-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_events', '0005_adgroup_adrisksnapshot_aduser_admemberof'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrisksnapshot',
            name='direct_members_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adrisksnapshot',
            name='findings_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adrisksnapshot',
            name='inactive_users_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
