# Generated by Django 5.1.5 on 2026-02-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_events', '0006_adrisksnapshot_direct_members_data_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='securityevent',
            name='security_ev_event_t_b8f125_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityevent',
            name='security_ev_severit_97ca43_idx',
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'severity'], name='security_ev_event_t_cc47ca_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'action'], name='security_ev_event_t_0af8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'app_category'], name='security_ev_event_t_f1d113_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'username'], name='security_ev_event_t_b1f384_idx'),
        ),
    ]
