# Generated by Django 5.1.5 on 2026-02-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_events', '0007_remove_securityevent_security_ev_event_t_b8f125_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'attack_name'], name='security_ev_event_t_f687f2_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'virus_name'], name='security_ev_event_t_0c94d7_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='security_ev_event_t_013b6f_idx'),
        ),
    ]
