# Generated by Django 5.1.5 on 2026-02-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_events', '0008_securityevent_security_ev_event_t_f687f2_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'category'], name='security_ev_event_t_92fb43_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'src_ip'], name='security_ev_event_t_e2ff41_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'dst_ip'], name='security_ev_event_t_060596_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'app_name'], name='security_ev_event_t_354c85_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'app_risk'], name='security_ev_event_t_b99c83_idx'),
        ),
    ]
