# Generated by Django 5.1.5 on 2026-02-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_events', '0008_securityevent_security_ev_event_t_f687f2_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'url'], name='security_ev_event_t_e716b2_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'category'], name='security_ev_event_t_92fb43_idx'),
        ),
    ]
