# Generated by Django 5.1.5 on 2026-02-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_events', '0009_securityevent_security_ev_event_t_92fb43_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='hostname',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'hostname'], name='security_ev_event_t_6b7020_idx'),
        ),
    ]
