# Generated by Django 5.1.5 on 2026-02-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_events', '0010_securityevent_hostname_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adauthevent',
            index=models.Index(fields=['timestamp', 'workstation'], name='security_ev_timesta_51b933_idx'),
        ),
        migrations.AddIndex(
            model_name='adauthevent',
            index=models.Index(fields=['timestamp', 'src_ip'], name='security_ev_timesta_afc29b_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'src_country'], name='security_ev_event_t_4931a8_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'cve'], name='security_ev_event_t_4ac639_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'file_name'], name='security_ev_event_t_7651c8_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'file_hash'], name='security_ev_event_t_60938b_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'ad_display_name'], name='security_ev_event_t_47e51a_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'date', 'user_department'], name='security_ev_event_t_b03d37_idx'),
        ),
    ]
